SzFMV2018-Tavasz/AutomatedCar

- README.md
> add my name to readme

- README.md
> Name added to README.md

- src/main/java/hu/oe/nik/szfmv/Main.java
- src/main/java/hu/oe/nik/szfmv/XmlObject.java
- src/test/java/hu/oe/nik/szfmv/XmlObjectTest.java
I have done the dummy task. All the test passed.
- Xml object is working
> dummyTask is ready, new XML Object has been introduced

- README.md
> readme name add

- .github/CODEOWNERS
- src/main/java/hu/oe/nik/szfmv/common/Utils.java
- src/main/java/hu/oe/nik/szfmv/environment/Collidable.java
- src/main/java/hu/oe/nik/szfmv/environment/Crossable.java
- src/main/java/hu/oe/nik/szfmv/environment/Crosswalk.java
- src/main/java/hu/oe/nik/szfmv/environment/Movable.java
- src/main/java/hu/oe/nik/szfmv/environment/ParkingSpot.java
- src/main/java/hu/oe/nik/szfmv/environment/Road.java
- src/main/java/hu/oe/nik/szfmv/environment/RoadSign.java
- src/main/java/hu/oe/nik/szfmv/environment/Stationary.java
- src/main/java/hu/oe/nik/szfmv/environment/Tree.java
- src/main/java/hu/oe/nik/szfmv/environment/Visualizing.java
- src/main/java/hu/oe/nik/szfmv/environment/World.java
- src/main/resources/test.xml
- src/test/java/hu/oe/nik/szfmv/common/UtilsTest.java
Created function to read xml, and return list of WorldObjects described in #79
Merged  from other working branch to help test functionality:
Created function to parse xml object to WorldObject described in #95
Affected Tickets: #79 / #95 
Estimated time: 4h / 2h
Actual time : 4h / 4h
Difficulty: 5/5
Co-authored-by: @konyetamas 
Co-authored-by: @markmarics 
Co-authored-by: @tamasiscoming
> Team1 build from xml

- src/main/java/hu/oe/nik/szfmv/common/Utils.java
- src/main/java/hu/oe/nik/szfmv/visualization/CourseDisplay.java
- src/main/resources/reference_points.xml
- src/test/java/hu/oe/nik/szfmv/common/UtilsTest.java
Added reference point description xml to resources.
- CourseDisplay class can load the reference point coordinates for all images. #30
> Team2 referencepoints

- src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/VirtualFunctionBus.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/InputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/ReadOnlyInputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/enums/GearEnum.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Driver.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/SteeringWheel.java
- src/main/java/hu/oe/nik/szfmv/visualization/Gui.java
> Team3 steeringwheel

- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/InputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/GearShift.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/SteeringWheel.java
#40 
Megcsináltam a Váltó rendszert.
Létrehoztam egy GearShift osztáylt illetv ezt behuztam az InputHendlerbe.  
A Input Packeget singeltonná tettem.
@SzFMV2018-Tavasz/team3
> GearShicher Done

- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/InputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/ReadOnlyInputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/enums/GearEnum.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Driver.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/GasBrake.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/GearShift.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/SteeringWheel.java
- src/main/java/hu/oe/nik/szfmv/visualization/Gui.java
> Directory Input renamed to input

- src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
- src/test/java/hu/oe/nik/szfmv/visualization/DashboardTest.java
> kormányállás, sebességváltó megjelenítése

- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/InputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Index.java
Megcsináltama az Indexet
Ehhez szerkesztettem az Input Packeget.
Hozzá adtam Egy Index nevű osztályt is.
> Turn Signal Done

- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/InputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/LaneKeeping.java
> Lanekeeping gomb

- src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
- src/test/java/hu/oe/nik/szfmv/visualization/DashboardTest.java
updateDisplayedValues() fv.-be, beállítom a hátteret.
initializeDashboard() fv.-be inicializálok.
új fv.-k:
initializeLka()
initializePp()
> Lane keeping és parking gomb megjelenítés

- src/main/java/hu/oe/nik/szfmv/Main.java
- src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
- Buttons for ACC features #138 
- Updated Main.java so that updateDisplayedValues is called
- Code refactored
> Dashboard final touches

- src/main/java/hu/oe/nik/szfmv/visualization/CourseDisplay.java
> Course moving basics

- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/InputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ParkingPilote.java
> ParkingPiloteKeydown Added

- src/main/java/hu/oe/nik/szfmv/Steering.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/CarHeadingTest.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/CarPositionTest.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/SteerAngleTest.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/WheelDisplacementTest.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/WheelPositionTest.java
Tests for car position, heading, wheel displacement, and vector calculations
> Team6 steering1 tests

- src/main/java/hu/oe/nik/szfmv/Steering.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
Calculate new positiion of the car
> Team6 steering1

- checkstyle.xml
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/sample/ReadOnlySamplePacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/sample/SamplePacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/powertrain/PowertrainPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/powertrain/ReadOnlyPowertrainPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/CarSpecifications.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/PowertrainSystem.java
- src/main/java/hu/oe/nik/szfmv/visualization/CourseDisplay.java
- src/main/java/hu/oe/nik/szfmv/visualization/DrawUtils.java
- src/main/resources/lane_keeping_test_world.xml
- src/main/resources/reference_points.xml
- src/main/resources/test_world.xml
- src/test/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/PowertrainSystemTest.java
- Embed for UnitTest
- Create test cases
- Merge from master
- Issue #169
> Team5 sprint1 issue #169

- src/main/java/hu/oe/nik/szfmv/detector/interfaces/ICamera.java
- src/main/java/hu/oe/nik/szfmv/detector/interfaces/IRadarUltrasonic.java
Implementáljon egy olyan interface-t, amely három pont alapján meghatározza a közé eső Collidable objecteket és visszaadja egy listába
Implementáljon egy olyan interface-t, amely három pont alapján meghatározza a közé eső world objecteket és visszaadja egy listába
DoD:
-Interface
-Funkció magyarázó kommentek
Becsült idő: 4h
Nehézség: 2/5
Issue: Implement #180 , #181 
Co-authored-by: @tamasiscoming 
Co-authored-by: @lahunyady
> merge to team1 (interfaces implementation)

- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/InputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ACC.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/GasBrake.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/GearShift.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Index.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/LaneKeeping.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/SteeringWheel.java
> CodeRefactor

- src/main/java/hu/oe/nik/szfmv/detector/classes/Detector.java
- src/main/java/hu/oe/nik/szfmv/environment/World.java
Leírás:
Készítsen Detector osztályt, amely megvalósítja a #180 #181 -ben készített interfaceket. az osztályban tárolja le a vizsgált listát, amit egy Setterrel lehet beállítani.
készítsen egy Detector példányt, a World-ben getterrel, setterrel
DoD:
Detector osztály
Detector példány
Magyarázó kommentek
Becsült idő: 2h
Aktuális idő: 1h
Nehézség: 2/5
Issue: #204
Co-authored-by: @angyantamas
Co-authored-by: @uhrindam
> Detector Class

- src/main/java/hu/oe/nik/szfmv/detector/classes/Detector.java
Fixed changes requested in pull request
Co-authored-by: @uhrindam
> Fixed changes requested in pull request

- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/InputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ACC.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/GasBrake.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/GearShift.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Index.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/LaneKeeping.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ParkingPilote.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/SteeringWheel.java
> CheckStyle-.-

- src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
- #167 (Hopefully) fixed the positions of the buttons because they appeared wrong at the demo
> (Hopefully) fixed the positions of the buttons

- src/main/java/hu/oe/nik/szfmv/detector/classes/Detector.java
- src/main/java/hu/oe/nik/szfmv/environment/WorldObject.java
> Team1 some functionality

- src/main/java/hu/oe/nik/szfmv/Main.java
- src/main/java/hu/oe/nik/szfmv/Steering.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/SteeringMethods.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/VirtualFunctionBus.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/car/CarPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/car/ReadOnlyCarPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/SteeringSystem.java
- src/main/java/hu/oe/nik/szfmv/environment/models/Pedestrian.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/CarHeadingTest.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/CarPositionTest.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/SteerAngleTest.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/WheelDisplacementTest.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/WheelPositionTest.java
- src/test/java/hu/oe/nik/szfmv/environment/models/PedestrianTest.java
> Team6 sprint2 branch refactoring

- src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
> A gombok többé nem fókuszálhatóak, így az inputhandler működhet

- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/CarSpecifications.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/PowertrainSystem.java
- src/main/java/hu/oe/nik/szfmv/detector/classes/Detector.java
- src/main/java/hu/oe/nik/szfmv/detector/interfaces/ICamera.java
- src/main/java/hu/oe/nik/szfmv/detector/interfaces/IRadarUltrasonic.java
- src/main/java/hu/oe/nik/szfmv/environment/World.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/PowertrainSystemTest.java
Fixing the #229 bug, and fine tuning the gearbox
> Team5 #229 bugfix

- src/main/java/hu/oe/nik/szfmv/detector/classes/Detector.java
- src/main/java/hu/oe/nik/szfmv/environment/WorldObject.java
- src/main/java/hu/oe/nik/szfmv/environment/XmlToModelConverter.java
- src/main/java/hu/oe/nik/szfmv/environment/models/RoadSign.java
- src/main/java/hu/oe/nik/szfmv/environment/models/Tree.java
- src/main/java/hu/oe/nik/szfmv/visualization/CourseDisplay.java
> Team1 world object shape project

- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/CarSpecifications.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/PowertrainSystem.java
- src/main/java/hu/oe/nik/szfmv/environment/World.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/PowertrainSystemTest.java
#Summary of changes and the sender team
- Issue #216: when PowertrainSystem.carCollide(); method called, the car slow down 30 percent of the speed
- Added some UnitTest for the new function
- modify enginebrake, brakeforce value for the better gameplay. Issue #252
> Team5 sprint2 issue #216 sebesseg lassitas utkozeskor

- src/main/java/hu/oe/nik/szfmv/detector/classes/Triangle.java
- src/test/java/hu/oe/nik/szfmv/detector/TriangleTest.java
- Create triangle #193 
- Tests for the **Triangle class**
- https://gist.github.com/sirnye/bdfaef8a3b4c006b0add28d69df28bde
> Triangle creator class

- src/main/java/hu/oe/nik/szfmv/environment/WorldObject.java
- src/main/java/hu/oe/nik/szfmv/environment/models/Road.java
> Team1 road object poligons 247

- src/main/java/hu/oe/nik/szfmv/environment/models/RoadSign.java
- src/main/java/hu/oe/nik/szfmv/environment/models/Tree.java
- src/test/java/hu/oe/nik/szfmv/detector/DetectorTest.java
- src/test/java/hu/oe/nik/szfmv/environment/models/MovableTest.java
> Detector test

- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/SensorsVisualizer.java
Egyszerűsítettem a Vizualizer osztályban egy elágazást.
> Reduce code complexity

- src/main/java/hu/oe/nik/szfmv/environment/World.java
- Detecor changed to static in World class #224 
- Shared Detector available for everyone #274 
-Triangle class already functions as a factory #193
> Trianglefactory and collision detection function

- src/main/java/hu/oe/nik/szfmv/automatedcar/sensors/UltrasonicSensor.java
- Update function has been added. #191
> Created function to update sensors.

- src/main/java/hu/oe/nik/szfmv/detector/classes/FrontBackDetector.java
- src/main/java/hu/oe/nik/szfmv/detector/classes/RoadLaneDetector.java
- src/main/java/hu/oe/nik/szfmv/environment/WorldObject.java
> Team3 utsav

- src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
- Controls are displayed on dashboard #273 
- Speed is no longer displayed as negative when car is in reverse
> Team4 sprint2 273 dashboard fixes

- src/main/java/hu/oe/nik/szfmv/Main.java
- src/main/java/hu/oe/nik/szfmv/environment/World.java
- src/main/java/hu/oe/nik/szfmv/environment/WorldObject.java
- src/test/java/hu/oe/nik/szfmv/environment/WorldTest.java
- base structure of the collision detection implemented in Main.cs and World.cs  #217
> Team5 sprint2 issue#217

- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/InputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/ReadOnlyInputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/SensorsVisualizer.java
- src/test/java/hu/oe/nik/szfmv/visualization/DashboardTest.java
Az Inputot bővitettem, hogy a shapek határának a kirajzolsára is legyen egy külön gomb.
A 6-os billenytűvel lehet ezt kezelni.
@SzFMV2018-Tavasz/team2
> Shape Border Vizualizer

- .github/stale.yml
- src/main/java/hu/oe/nik/szfmv/Main.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/InputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/ReadOnlyInputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/SensorsVisualizer.java
- src/main/java/hu/oe/nik/szfmv/detector/classes/FrontBackDetector.java
- src/main/java/hu/oe/nik/szfmv/detector/classes/RoadLaneDetector.java
- src/main/java/hu/oe/nik/szfmv/environment/World.java
- src/main/java/hu/oe/nik/szfmv/environment/WorldObject.java
- src/main/java/hu/oe/nik/szfmv/environment/XmlToModelConverter.java
- src/main/java/hu/oe/nik/szfmv/environment/models/Movable.java
- src/main/java/hu/oe/nik/szfmv/environment/models/Pedestrian.java
- src/main/java/hu/oe/nik/szfmv/environment/models/Road.java
- src/main/java/hu/oe/nik/szfmv/environment/models/RoadSign.java
- src/main/java/hu/oe/nik/szfmv/visualization/CourseDisplay.java
- src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
- src/main/java/hu/oe/nik/szfmv/visualization/ReferencePointStore.java
- src/test/java/hu/oe/nik/szfmv/environment/models/PedestrianTest.java
- src/test/java/hu/oe/nik/szfmv/visualization/DashboardTest.java
- NPC car
- Predestrian
- Mergeable to master
> Team6 sprint2 merged

- src/main/java/hu/oe/nik/szfmv/Main.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/sensors/UltrasonicSensor.java
- src/main/java/hu/oe/nik/szfmv/common/Utils.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/sensors/UltrasonicSensorTest.java
- src/test/java/hu/oe/nik/szfmv/common/UtilsTest.java
- Created an ultrasonic sensor class #194
- Sensor can return nearest object #189
- Sensor can return the distance of the nearest object #189
- Sensor can return the dimensions of the nearest object #189
- Added a new method to Utils.java that can determine the distance between two 2D coordinates
- Added a new method to Utils.java that can convert meters to pixels
- Added test for all of the above
> Ultrasonic Sensor functionality added

- src/main/java/hu/oe/nik/szfmv/Main.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/sensors/UltrasonicSensor.java
- src/main/java/hu/oe/nik/szfmv/detector/classes/Detector.java
- src/main/java/hu/oe/nik/szfmv/environment/World.java
- src/test/java/hu/oe/nik/szfmv/detector/DetectorTest.java
- changed Detector class calling 
- Detector class has getDetector which gives back a Detector
- instead of world.getDetector have to use Detector.getDetector
- DetectorTest changed
> Changing Detector

- src/main/java/hu/oe/nik/szfmv/Main.java
- src/main/java/hu/oe/nik/szfmv/common/SortVertices.java
- src/main/java/hu/oe/nik/szfmv/environment/models/NpcCar.java
Checkstyle fixes and rounding for pull request (#333 ) to master
> Checkstyle fixes and rounding

- src/main/java/hu/oe/nik/szfmv/Main.java
- src/main/java/hu/oe/nik/szfmv/environment/World.java
fixing while condition in Main.java while loop (isGameOver)
> fixing while condition in Main.java while loop (isGameOver)

- src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/VirtualFunctionBus.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/reverseradar/ReadOnlyReverseRadarPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/reverseradar/ReverseRadarPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ReverseRadar.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ReverseRadarState.java
- src/main/java/hu/oe/nik/szfmv/common/SortVertices.java
- src/main/java/hu/oe/nik/szfmv/environment/WorldObject.java
- src/main/java/hu/oe/nik/szfmv/environment/XmlToModelConverter.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/bus/VirtualFunctionBusTest.java
- ReverseRadar prepared, still don't calculates rear object distance, but activating in R state and send signals on VitualFunctionBus
- Added ReverseRadarPacket and instantiated to VirtualFunctionBus
- Some refactoring and checkstyle fix
> Team5 Sprint3 (prepare Reverse Radar) issue#350

- src/main/java/hu/oe/nik/szfmv/automatedcar/sensors/UltrasonicSensor.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/sensors/UltrasonicSensorTest.java
- Removed updateSensor() method as it was not working as intended (#191).
- Replaced getX() and getY() methods with getPosition() which now correctly calculates the position of the sensor on the car (#330).
- Created a test to see if rotation works as intended.
> Ultrasonic sensor methods now use the correct placement on the car

- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ParkingPilotFunction.java
- new java class for ParkingPilot functions #342
> new class for PP

- src/main/java/hu/oe/nik/szfmv/Main.java
> Created parking car NPCs.

- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/detector/RadarSensorPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/detector/ReadOnlyRadarSensorPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/RoadLaneDetector.java
> Team3 radarsensor traingle

- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ACC.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Index.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ParkingPilote.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/RoadLaneDetector.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/SensorsVisualizer.java
> Team3 acc +/- keycode

- src/main/java/hu/oe/nik/szfmv/Main.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/detector/RadarSensorPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/detector/ReadOnlyRadarSensorPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/RoadSignDetection.java
- src/main/java/hu/oe/nik/szfmv/visualization/CourseDisplay.java
- Display of sensor ranges (issue #234)
> Team2 sensor debug display

- src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/detector/RadarSensorPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/detector/ReadOnlyRadarSensorPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ACC.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/FrontBackDetector.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Index.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ParkingPilote.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/RoadLaneDetector.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/SensorsVisualizer.java
> Team3 radar traingle

- src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
- Fixing radar display font size on Dashboard (#407 change request)
> PR#407 change request fixing

- src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/detector/RadarSensorPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/detector/ReadOnlyRadarSensorPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/InputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/ReadOnlyInputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ACC.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/FrontBackDetector.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Index.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ParkingPilote.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/RoadLaneDetector.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/SensorsVisualizer.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/TrackingBut.java
- src/main/java/hu/oe/nik/szfmv/environment/World.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/CarHeadingTest.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/CarPositionTest.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/SteerAngleTest.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/WheelDisplacementTest.java
- src/test/java/hu/oe/nik/szfmv/automatedcar/steering/WheelPositionTest.java
- src/test/java/hu/oe/nik/szfmv/visualization/DashboardTest.java
> Team3 trackingbutton added

- src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/input/InputHandler.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/EmergencyBrake.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/FrontBackDetector.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/GasBrake.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/RoadLaneDetector.java
> Team3 EmergencyBrake added

- src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/InputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/input/ReadOnlyInputPacket.java
- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/LaneKeepAssistant.java
- src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
- src/test/java/hu/oe/nik/szfmv/visualization/DashboardTest.java
LKA checks if it can be used, changes LKA button color accordingly, little changes and fixes
> team2_sprint3_LKA_button to team2

- src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/LaneKeepAssistant.java
implementing turn right and left
> Lanekeeping
